### PR TITLE
Attempt at fixing #70

### PR DESCRIPTION
**Pull request by ottonemo**
Use `torch.load` so we can use the location mapping feature
which enables us to remap GPU storage to CPU storage.

### CODE REVIEW

**Comment by benjamin-work** [comment]
This does not work currently because `optim_` has references to the model parameters, which are still on cuda. We need to treat `optim_` separately (maybe have a list of keys that need to be treated separately).

In addition, we should skip all tests that require cuda (`pytest.mark.skipf(...)`) when cuda is not available.

**Comment by benjamin-work** [comment]
@ottonemo please have a look

**Comment by ottonemo** [comment]
LGTM

**Comment by ottonemo** [comment]
LGTM

**Pull request merged**
